### ISSUE TITLE
Unstick sticky footer - 721

### ISSUE THREAD

**Issue by burnsben** [0xProject/0x-launch-kit-frontend#486]
Footer shouldn't go above the content. have this 0x logo show at the bottom of the page underneath all of the content. 
<img width="484" alt="Screen Shot 2019-05-28 at 5 00 16 PM" src="https://user-images.githubusercontent.com/29830192/58519848-1d52e880-816a-11e9-9ff8-90720ad91157.png">

**Comment by gabitoesmiapodo** [comment]
@burnsben 

Could you expand on how you intend this to work? Should the whole section's height grow freely?

I need to be sure because I don't think this is a trivial change: layout is shared between ERC721 and ERC20, so ERC721 inherits the original layout with a fixed height equal to the screen's. Content scrolls between header and footer in this configuration.

If we need different behaviors it may be necessary to create separate layouts (not sure about this yet).

**Comment by chriskalani** [comment]
Since the content doesn't scroll on ERC-20 it is fine for the footer to always be at the bottom of the viewport. But since ERC-721 does scroll, it doesn't make sense to have content scroll *behind* the footer. The footer should just come after the content, i.e. it would not show up on the page in the event the page scrolls.
