### ISSUE TITLE
ETH:wETH Converting error

### ISSUE THREAD

**Issue by burnsben** [0xProject/0x-launch-kit-frontend#503]
ETH:wETH conversion is a bit jank at the moment

Getting this error after trying to wrap eth. 
<img width="413" alt="Screen Shot 2019-05-30 at 10 27 20 AM" src="https://user-images.githubusercontent.com/29830192/58651448-37094280-82c6-11e9-8ae4-37d78c373fd3.png">

Also this happened yesterday
<img width="490" alt="Screen Shot 2019-05-29 at 2 24 02 PM" src="https://user-images.githubusercontent.com/29830192/58651463-412b4100-82c6-11e9-98eb-375e4c79c061.png">

**Comment by burnsben** [comment]
^for that second screenshot, those weren't my actual balances, it changed to 100 wETH randomly.

**Comment by mariano-aguero** [comment]
Hi @burnsben, 
I think the problem is that previously there was an account change on metamask, and the account was not reset before the transaction, could you tell me if the problem persists? In case of Yes, could you share the steps to reproduce the issue?. 

Regards

![Screenshot_20190531_142801](https://user-images.githubusercontent.com/1144028/58723823-647eea80-83b1-11e9-92e5-fea031f8d19e.png)

**Comment by burnsben** [comment]
Not sure what you mean by account change, the only changes I've made in metamask are switching from mainnet to kovan. 

Problems happen when I go back and forth between converting. 

Here, I only have 7.33 ETH, but it's showing an inflated total
<img width="354" alt="Screen Shot 2019-05-31 at 12 31 35 PM" src="https://user-images.githubusercontent.com/29830192/58730307-963b8580-83a0-11e9-84ff-cafced5c2b6b.png">

**Comment by burnsben** [comment]
Going from full 7.33 ETH, to a split of ETH: wETH gave me this error again
<img width="347" alt="Screen Shot 2019-05-31 at 12 26 37 PM" src="https://user-images.githubusercontent.com/29830192/58730327-a7849200-83a0-11e9-99d1-0d863babe0a5.png">

**Comment by burnsben** [comment]
wait sorry I got that reversed, that was trying to go from a split to full 7.33 ETH

**Comment by burnsben** [comment]
the issue of showing the 10.3 amount is temporary-- there's a lag in calculating the individual amounts.

**Comment by unjapones** [comment]
@burnsben the UI allows to open the conversion modal and funky things may happen while the wrap transaction is still pending. Just to name one, the ETH/WETH balances shown are not _100% accurate_ since a wrap is happening.

Should we disable the button that opens the wrap modal until the transaction has been confirmed? I believe this will reduce the chance of unexpected events.

**Comment by burnsben** [comment]
@unjapones These errors happen after it says the transaction has completed successfully. Perhaps these success states are not correct? 
<img width="432" alt="Screen Shot 2019-06-04 at 10 28 47 AM" src="https://user-images.githubusercontent.com/29830192/58900360-e3c33580-86b3-11e9-9db6-5046d86c4582.png">
