### ISSUE TITLE
Shouldn't need to unlock with when you're making a market buy 

### ISSUE THREAD

**Issue by burnsben** [0xProject/0x-launch-kit-frontend#505]
<img width="950" alt="Screen Shot 2019-05-30 at 12 46 15 PM" src="https://user-images.githubusercontent.com/29830192/58659947-0f6fa580-82d9-11e9-8685-25ba7518be30.png">

This should generally default to using ETH with the forwarder contract. Shouldn't need to unlock wETH.

**Comment by fvictorio** [comment]
We only use the forwarder contract in the erc721 marketplace. Should we work on changing this?

**Comment by burnsben** [comment]
Yes. The erc20 marketplace needs this for market buys. We were under the impression that this would be included in the MVP. We highlighted this in the blog post as one of the features.

**Comment by burnsben** [comment]
<img width="427" alt="Screen Shot 2019-05-31 at 3 22 15 PM" src="https://user-images.githubusercontent.com/29830192/58737826-e40fb800-83b7-11e9-96c6-c1545f162600.png">
Shouldn't need to convert or unlock.

**Comment by mariano-aguero** [comment]
There is a work in progress in this branch `hotfix/add-fowarder-contract-to-market-buy`

**Comment by unjapones** [comment]
@burnsben we have a WIP branch that uses the forwarder and we found an edgy case. Let's assume the following:

1. The user has `5 ETH` + `5 wETH` = `10 ETH + wETH` total balance.
2. Wants to perform a market buy that requires `10 ETH`.
3. MetaMaksk shows that the contract interaction involves `10 ETH` and that the account doesn't have enough funds

In this case, he/she would need to _unwrap_ ETH in order to perform the action. We can insert the wrap eth step somewhere in the flow, but is not that a little bit odd?

**Comment by unjapones** [comment]
Just in case, the anwser for the above was:

- If available `ETH` is enough to perform the buy, use the forwarder.
- If available `ETH` is NOT enough, but `ETH + wET` balance is, append the "wrap ether" step in the flow and use `wETH`.

This was also added to the PR #549 description.
