### ISSUE TITLE
Adding new custom token .svg icons does not work

### ISSUE THREAD

**Issue by icinsight** [0xProject/0x-launch-kit-frontend#517]
For some reason, I'm not able to add new token.svg icons. I can change existing ones, but as soon as it is the question of token that I added myself (i.e. not one of those in the repo already), the system renders a "color ball + symbol" icon, even though a fully functional .svg file for that token is there.

![image](https://user-images.githubusercontent.com/39129866/58769820-1587af80-8581-11e9-873a-d94588d67b11.png)

![image](https://user-images.githubusercontent.com/39129866/58769839-5ed7ff00-8581-11e9-8d8a-bba456576d81.png)

**Comment by unjapones** [comment]
@icinsight I'm afraid that, because of [the way we load SVG files](https://facebook.github.io/create-react-app/docs/adding-images-fonts-and-files) you will have to:

1. add the file to the corresponding location (you already did this).
2. modify a little bit the source code, `import` that file and add it here [`src/components/common/icons/token_icon.tsx`](https://github.com/0xProject/0x-launch-kit-frontend/blob/development/src/components/common/icons/token_icon.tsx#L42).

Did the above help? If it did, it may be a good idea to add this to the docs.

**Comment by icinsight** [comment]
Ok, I may have missed the token_icon.tsx file. Thanks!

Just update your documentation, and I will do the same with mine!

**Comment by icinsight** [comment]
I got this working just fine: http://dex.0xchange.org:3002/#/erc20/my-wallet?base=king&quote=xbc
