### ISSUE TITLE
Limit orders won't get matched

### ISSUE THREAD

**Issue by icinsight** [0xProject/0x-launch-kit-frontend#551]
As seen in the picture, matching buy-sell limit orders won't meet and trade won't take place.

The same happens when the limit buy order is HIGHER than the lowest sell order.

Market order executes correctly.

![image](https://user-images.githubusercontent.com/39129866/59981348-471bf580-95d8-11e9-9237-cd9f3034fed7.png)

**Comment by icinsight** [comment]
See this for "negative" spread non-match.

![image](https://user-images.githubusercontent.com/39129866/59981415-59e2fa00-95d9-11e9-9b00-6c622c97aa2c.png)

**Comment by tomhschmidt** [comment]
The current Launch Kit backend implementation is just an open orderbook relayer, so it's not matching orders by design. Bots can match overlapping orders together and collect the spread by calling matchOrders, and we find that this generally happens quite quickly on OO relayers.

Might be nice to warn people who are placing a limit order above the spread to use a market order instead (?), but this is working as intended for now.

**Comment by icinsight** [comment]
Market orders work, but not even matching orders execute, see the first screen. If that is a "feature" I'm fine with that. It means one can't really buy using limit orders, right? That is odd feature but we can live with that.

**Comment by tomhschmidt** [comment]
Yeah, this is by design. Open orderbook relayers have no "matching engine" that would actually fill the orders and pay for the gas. Users can do it themselves, or bots can find orders that overlap and fill them to capture the spread https://0x.org/wiki#Open-Orderbook

**Comment by icinsight** [comment]
Ok. So a market order is the only way to buy, right?
